### ISSUE TITLE
Issue with manifest file

### ISSUE THREAD

**Issue by ShreyashPromact** [omaflak/FingerprintDialog#1]
There is some issue while adding this library to project.
I have multiple libraries added to my own project. Now, when I add this library, I show manifest merger error.
This might be because the library using some provider that conflict to existing providers (Not sure).

Please look at this issue and resolved it.

Thanks.

**Comment by omaraflak** [comment]
Hi, thank you for reporting this error but I can't seem to reproduce the issue. When I create a whole new project and include the library in it, everything works.
Which means, in some way, another of your included libraries is conflicting with mine. 

Can you send me a list of the libraries you included ? Any error message would be also helpful.

**Comment by Thisishowwedoit-2Moons** [comment]
You probably use a minSdk lower then 23 as me, you simply have to add this in your manifest 
<uses-sdk tools:overrideLibrary="me.aflak.libraries" />

and be sure to precheck in your activities the build sdk > 23 to call this library

Sincerely,
