### ISSUE TITLE
Cancel dialog

### ISSUE THREAD

**Issue by ivanpajon** [omaflak/FingerprintDialog#2]
Hello, I am trying to cancel the fingerprint dialog when reach a limit with tryLimit() but I have no idea what does this function. I need some help please. Here is an extract of my code.
``FingerprintDialog.initialize(this).tryLimit(1, () -> Toast.makeText(getApplicationContext(), "Has alcanzado el limite máximo de intentos", Toast.LENGTH_LONG).show())``

**Comment by omaraflak** [comment]
Hi. You are right there is no way to cancel the dialog for now, I will add this feature today.

**Comment by ivanpajon** [comment]
Thanks a lot! You save my week 😄

**Comment by omaraflak** [comment]
@ivanzhenlms I just added the feature and updated the library. You can use the new version : 

`implementation 'me.aflak.libraries:fingerprint:2.5.3'`

And this is what you would do : 

```
if(FingerprintDialog.isAvailable(this)) {
    FingerprintDialog.initialize(this)
        .title(R.string.fingerprint_title)
        .message(R.string.fingerprint_message)
        .callback(this)
        .tryLimit(1, new FailAuthCounterDialogCallback() {
            @Override
            public void onTryLimitReached(FingerprintDialog fingerprintDialog) {
                fingerprintDialog.dismiss();
            }
        })
        .show();
}
```

**Comment by ivanpajon** [comment]
Hi @OmarAflak ,

Using `.cancelOnPressBack(true)` and `.cancelOnTouchOutside(true)` in the FingerprintDialog I can't catch when user cancels it, dialog only disappear. Can you add implementation with `onAuthenticationCancel()` in `.callback(this)` ?

Sorry for the inconveniences man :disappointed:
