### ISSUE TITLE
how to open next activity 

### ISSUE THREAD

**Issue by mustafamn** [omaflak/FingerprintDialog#3]
i want to open next activity with finger print how to do that with out  Crypto Object

**Comment by omaraflak** [comment]
Look at the examples in the README.

```java
if(FingerprintDialog.isAvailable(this)) {
	FingerprintDialog.initialize(this)
	    .title(R.string.fingerprint_title)
	    .message(R.string.fingerprint_message)
	    .callback(new FingerprintDialogCallback(){
	        @Override
		    public void onAuthenticationSucceeded() {
		        Intent intent = new Intent(MainActivity.this, NewActivity.class);
		        startActivity(intent);
		        finish();
		    }

		    @Override
		    public void onAuthenticationCancel() {}
	    }).show();
}
```

**Comment by mustafamn** [comment]
Thanks for the reply and i have successfully done with this but i have one
more question or problem i have use  this in Alert dialog box when
onAuthenticationSucceeded
and open newActivity it done with this but coming back to mainActivity the
dialog does not dismiss from there.??? i used dialog.dismiss(); but showing
error on dismiss(); can you solve this problem?

**Comment by omaraflak** [comment]
I am not sure to understand what you are saying.

> the dialog does not dismiss

Are you talking about the Fingerprint Dialog ?  I mean the dialog from the library ?
