### ISSUE TITLE
Automatically scanning

### ISSUE THREAD

**Issue by romilcresol** [omaflak/FingerprintDialog#5]
I have used it in my own Dialog box, when I open the Dialog box the first time then it works perfectly. But when I open my Dialog after dismiss it then it scans fingerprint automatic and calls method "onAuthenticationError" called with error code "5" and the error message "Fingerprint Operation cancelled".

**Comment by omaraflak** [comment]
Hi @romilcresol, thank you for the feedback. This message is usually displayed when the fingerprint scanner is still occupied by a previous request. You need to cancel that request if you dismiss the dialog :
```java
fingerprint.cancel();
```

PS : You can take a look at [FingerprintDialog.java](https://github.com/OmarAflak/Fingerprint/blob/master/fingerprint/src/main/java/me/aflak/libraries/dialog/FingerprintDialog.java) to see how I made the default dialog box work.
