### ISSUE TITLE
Deprecation Notice

### ISSUE THREAD

**Issue by fkirc** [omaflak/FingerprintDialog#9]
To make it easier for the newcomers:
This library is deprecated since the release of the androidx library for the `BiometricPrompt` API.

If you want to combine the BiometricPrompt API with a symmetric key,
then you can have a look at this fully functional Kotlin implementation:
https://github.com/fkirc/secure-zip-notes/

**Comment by omaraflak** [comment]
True, `FingerprintManager` was deprecated in API level 28.

For futur use, one could use this library to support API < 28, and `BiometricPrompt` for API >= 28.

**Comment by fkirc** [comment]
Fur future use, I recommend to simply use the androidx library for `BiometricPrompt`.

Therefore, there is no need for a fallback mode to support API < 28.

**Comment by omaraflak** [comment]
Yeah turns out there's a support for older APIs.

https://stackoverflow.com/a/53590143/5552022
